# Simple Netlify Configuration for Static HTML Site
[build]
  command = "echo 'Building static site...' && node build-netlify.js"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

# API endpoints
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"  
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"