version: '3.8'

services:
  4calc-app:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    container_name: 4calc-webapp
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.4calc.rule=Host(`4calc.yourdomain.com`)"
      - "traefik.http.routers.4calc.tls=true"
      - "traefik.http.routers.4calc.tls.certresolver=letsencrypt"
      - "traefik.http.services.4calc.loadbalancer.server.port=3000"

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: 4calc-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - 4calc-app
    profiles:
      - production

networks:
  default:
    name: 4calc-network